### ISSUE TITLE
Cannot read property '0' of undefined on node v 0.12

### ISSUE THREAD

**Issue by andrewdep** [felixge/node-couchdb#54]
We sometimes get this error on node v 0.12:
```
TypeError: Cannot read property '0' of undefined
    at IncomingMessage.<anonymous> (/home/vagrant/keli/node_modules/felix-couchdb/lib/couchdb.js:220:47)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11) [TypeError: Cannot read property '0' of undefined]
```

The exception points to this line in `couchdb.js`:
```javascript
          httpAgent.sockets[host + ':' + port][0].emit("agentRemove");
```
From what I can tell the `sockets` array has a different format in this version of node. Looking at the state of `httpAgent.sockets` just before the exception I see the format is actually `host + ':' + port + '::'`. There is also a new (since node v0.10) function on httpAgent called `getName(...)` that is probably better to use than a manually built string. Just the same, I've fixed the issue for us by changing that line to this:
```javascript
          var socketKey = (httpAgent.getName && httpAgent.getName({host: host, port: port, maxSockets: 1})) || (host + ':' + port + '::');
          (httpAgent.sockets[socketKey] || httpAgent.sockets[host + ':' + port])[0].emit("agentRemove");
```

This is a very careful fix as it tries to maintain backward compatibility. If you think this fix makes sense just let me know and I'll submit a pull request.
Thanks!

**Comment by mandric** [comment]
@andrewdep did you want to submit a PR?

**Comment by mandric** [comment]
Merged, this in https://github.com/felixge/node-couchdb/pull/55. @felixge can you push to npm please?
